### PR TITLE
Rollback boxed text changes

### PR DESCRIPTION
**Pull request by seanwiseman**
Reapply explicitly read files in binary mode

### CODE REVIEW

**Comment by seanwiseman** [comment]
This branch was based from https://github.com/elifesciences/elife-tools/commit/e7cb854b94a4290a73d5d29f936b4e0937cb463c

**Comment by giorgiosironi** [comment]
I see the commit that reapplies `rb`, but I would expect to see the inverse of https://github.com/elifesciences/elife-tools/pull/257/files too.

**Comment by seanwiseman** [comment]
I based the branch from https://github.com/elifesciences/elife-tools/commit/e7cb854b94a4290a73d5d29f936b4e0937cb463c which was the commit before @gnott 's changes so no need to revert them on this branch.

**Comment by giorgiosironi** [comment]
But once merging this into `develop`, only the new commit would be applied on top, as the older commits are already in there... hence why I think they need an explicit `git revert`.

This branch would suffice if we were to pin it directly into `bot-lax-adaptor/requirements.txt`, but that would be a fork and prevent other work on `elife-tools` so it's not desirable?

**Comment by seanwiseman** [comment]
OK `develop` is now reverted back to https://github.com/elifesciences/elife-tools/commit/e7cb854b94a4290a73d5d29f936b4e0937cb463c . Merging this branch will just reapply the read files in binary mode change.

**Comment by giorgiosironi** [comment]
Uhm this seems to me a problematic way to go to remove changes, as we lose history (https://github.com/elifesciences/elife-tools/commits/develop is missing when the breaking change was added and when it was removed). I would prefer to leave the `develop` branch as append-only and explicitly revert by adding commits like in https://github.com/elifesciences/builder-private/commit/d4d61bfbaf82e60e1b7594bc83f7fb60e65c8455 and that would make this PR unnecessary. :thinking:

**Comment by seanwiseman** [comment]
OK, I have reverted that commit (shown here https://github.com/elifesciences/elife-tools/commit/6a83ccdeae75f4575769375636cd4b240850369e). This should do it, the code in question is now not present in `develop`.

**Comment by seanwiseman** [comment]
I will close this PR as no longer needed.

**Pull request closed without merging**
