### PR TITLE
Format authorLine directly for mixed citation related article data.

### PR DESCRIPTION
**Pull request by gnott**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
The Jenkins failure looks like a charset encoding problem, trying to reproduce.

**Comment by giorgiosironi** [comment]
e.g. `elifetools.tests.test_parse_jats.TestParseJats.test_references_json_edge_cases_19` is producing
```
u'Schr\xc3\xb6dinger, LLC'
```
instead of
```
u'Schr\xf6dinger, LLC'
```
The expecation seems correct as the `ö` character in Unicode is the `f6` codepoint; what is being produced is its utf-8 representation as two bytes, but I believe the combination of the `u'...'` data type with UTF-8 data in it is wrong.

**Comment by giorgiosironi** [comment]
Deleting the workspace made the build green. Locally, where it's green, I have this venv:
```
$ pip freeze
appdirs==1.4.3
beautifulsoup4==4.3.2
coverage==3.7.1
coveralls==1.1
ddt==1.1.0
docopt==0.6.2
lxml==3.4.1
packaging==16.8
pyparsing==2.2.0
requests==2.11.1
six==1.10.0
slugify==0.0.1
unittest-xml-reporting==1.12.0
```
In the workspace that was failing, I had:
```
appdirs==1.4.3
beautifulsoup4==4.3.2
certifi==2017.4.17
chardet==3.0.3
coverage==3.7.1
coveralls==1.1
ddt==1.1.0
docopt==0.6.2
idna==2.5
lxml==3.4.1
packaging==16.8
pyparsing==2.2.0
requests==2.11.1
six==1.10.0
slugify==0.0.1
unittest-xml-reporting==1.12.0
urllib3==1.21.1
```
So I think that despite `requests` being pinned, the rest of the dependencies resulting from the broken `requests` version (which may very well be the cause) were left there.

**Comment by gnott** [comment]
Thanks for fixing it @giorgiosironi.

The test cases have been working fine up until the inclusion of chardet as part of requests dependencies, so I'm not sure any of the cases are incorrect in how they express the unicode characters.

One example is ``test_duplicate_tag()``, the same character is used in the input and expected output, e.g.

```
("<p>§ <italic>*</italic></p>", "paragraph", u"<p>§ <italic>*</italic></p>"),)
```

and the assertion fails due to these different encodings

```
AssertionError: u'<p>\xa7 <italic>*</italic></p>' != u'<p>\u0e22\u0e07 <italic>*</italic></p>'
```

The encoding of parsed data up until now has been pretty solid and we're not changing it here, so it should give us the results we've been reviewing for the past many months.

**Pull request merged**
