### PR TITLE
removed the beginnings of a very bad idea

### PR DESCRIPTION
**Pull request by lsh-0**
pinging @giorgiosironi @gnott

### CODE REVIEW

**Comment by giorgiosironi** [comment]
:+1: for avoiding global state, but I'm not sure where this variable was read and what will be read now instead, can you link a reference to it?

**Comment by lsh-0** [comment]
so in all of the instances found in elife-tools it looks like it was being shadowed by a parameter to the function. regardless as to how the code grew that way it needed to be pruned back. it was already infecting `bot-lax-adaptor`

```
./elifetools/tests/test_utils_html.py:67:    def test_xml_to_html(self, html_flag, xml_string, base_url, expected):
./elifetools/tests/test_utils_html.py:68:        self.assertEqual(utils_html.xml_to_html(html_flag, xml_string, base_url), expected)
./elifetools/utils_html.py:4:def xml_to_html(html_flag, xml_string, base_url=None):
./elifetools/utils_html.py:12:    html_string = replace_inline_graphic_tags(html_string, base_url)
./elifetools/utils_html.py:103:def replace_inline_graphic_tags(s, base_url=None):
./elifetools/utils_html.py:116:                # Add base_url if given
./elifetools/utils_html.py:117:                if base_url:
./elifetools/utils_html.py:118:                    xlink = base_url + xlink
```

**Comment by gnott** [comment]
I attempted to set the base_url once so it could be used by the parser. I can change this, I just need to pass the variable in around many different functions, and it will be more explicit.

**Comment by lsh-0** [comment]
yeah - nothing but pain that way. be safe, be explicit.

**Pull request merged**
