### PR TITLE
Version 0.2.0 bump, small changes to setup, readme

### PR DESCRIPTION
**Pull request by gnott**
Changes to bump the version up to ~`1.0.0`~ `0.2.0`, I updated the maintainer email in `setup.py` to be more current, and cleaned up some bits in the readme.

### CODE REVIEW

**Review by lsh-0 — APPROVED** [review]
just a reminder but the moment you hit `1.0.0` in semver you're committing to preserving the developer API as it is. Any breaking changes to this API require a major version bump.

**Comment by gnott** [comment]
Yes, thanks for the note. We've been using it with minimal changes for a long time now so I think it's an appropriate version number. That said, we might end up with a `2.0.0` very soon if we go back and restructure it as I'd hope we do.

**Comment by gnott** [comment]
Oh, I'm changing my mind now. I guess we don't need `1.0.0` yet in order to test our semver release plans. The reason I'm backtracking is I want to lint things before it's `1.0.0`. So, I guess I'm going to change this to `0.2.0`. I hope that's still acceptable for now @lsh-0 ?

**Comment by lsh-0** [comment]
it's fine ;)

good opportunity to give the code base a once-over

**Comment by lsh-0** [comment]
> Yes, thanks for the note. We've been using it with minimal changes for a long time now so I think it's an appropriate version number.

I agree

**Pull request merged**
