### PR TITLE
Build on both Python 2 and 3

### PR DESCRIPTION
**Pull request by giorgiosironi**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
As expected:

**Comment by giorgiosironi** [comment]
Wouldn't merge it in `develop`, but it can be merged in branches where 3.x support is being added.

**Comment by lsh-0** [comment]
using `tox` is also a possibility, moving the test configuration out of the jenkins file into a tox.ini file: https://bitbucket.org/lskibinski/et3/src/5aabdfce6cd6181a41b5cc37aec42d3052376d9b/tox.ini?at=default&fileviewer=file-view-default

**Comment by seanwiseman** [comment]
Yes`tox` is what I have been using locally so I would like to see if this can be integrated into the process.

**Comment by giorgiosironi** [comment]
Trying that today.

**Comment by giorgiosironi** [comment]
Now running on both versions with tox, but misteriously fails on 2.7.

**Comment by seanwiseman** [comment]
Closing PR as this has been included in https://github.com/elifesciences/elife-tools/pull/246

**Pull request closed without merging**
