### PR TITLE
clean up of utils.py and more added to rawJATS.py

### PR DESCRIPTION
**Pull request by lsh-0**
I've done a bit more major surgery, really sinking my teeth into the functions I shifted to utils.py
More raw extracts have been shifted to rawJATS.py and their corollaries updated in parseJATS.py
I've also shifted most of the smaller functions to the top of the module in parseJATS.py as I worked through them. I hope to just have those huge functions by themselves at the bottom composed mostly of the dead simple ones above it.

### CODE REVIEW

**Comment by gnott** [comment]
I think slugify needs to be added to the install requirements to pass the travis test.

**Comment by lsh-0** [comment]
Damn, forgot to add that. I'll fix if up and re send

**Comment by lsh-0** [comment]
yeah its misleading - it says the build is passing when its actually not.

On Sun, Apr 12, 2015 at 10:56 PM, Luke Skibinski <
l.skibinski@elifesciences.org> wrote:

> Damn, forgot to add that. I'll fix if up and re send
> On 12 Apr 2015 22:42, "Graham Nott" <notifications@github.com> wrote:
>
>> I think slugify needs to be added to the install requirements to pass the
>> travis test.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/elifesciences/elife-tools/pull/28#issuecomment-92137458>
>> .
>>
>


-- 

Luke Skibinski

Human being that
writes software,
manages systems.

--

eLife Sciences Publications, Ltd is a limited liability non-profit
non-stock corporation incorporated in the State of Delaware, USA, with
company number 5030732, and is registered in the UK with company number
FC030576 and branch number BR015634 at the address First Floor, 24 Hills
Road, Cambridge CB2 1JP.

**Comment by lsh-0** [comment]
fix is in. closing this pull request.

**Pull request closed without merging**
