### PR TITLE
Merge develop branch into master, version 0.6.1

### PR DESCRIPTION
**Pull request by gnott**
As part of configuring automated version releases to be sent to the pypi package index, the pipeline can be triggered by merging into the `master` branch. That branch has not been updated in a very long time, so this PR includes a bunch of commits going back to January of 2018.

### CODE REVIEW

**Comment by gnott** [comment]
Looks like I need 1 approving review please in order to merge into a protected branch, over to you please @lsh-0 or @NuclearRedeye

**Comment by lsh-0** [comment]
there are a lot of changes here, I'm guessing this is because it's been a while since `master` was updated?

I'm not sure what the state of Jenkins support for merging `develop` changes into `master` is for libraries but we might want to take a look at that later on as well.

**Comment by lsh-0** [comment]
I've deleted the branch protection rule for the `master` branch. I'm not sure why it was there but as the project maintainer I think you should have the agency to make these decisions yourself, @gnott .

**Review by lsh-0 — APPROVED** [review]
approved, but I didn't look at all of the changes.

**Comment by NuclearRedeye** [comment]
> I've deleted the branch protection rule for the master branch. I'm not sure why it was there but as the project maintainer I think you should have the agency to make these decisions yourself, @gnott .

I noticed while updating the maintainers files that some repo's have certain protections in place and others don't. Maintainers though should be able to decide/skirt these protections though. I'll add an extra item to the checklist in elifesciences/issues#6491 to cover making sure that maintainers can manage repo settings.

**Review by NuclearRedeye — APPROVED** [review]
I've had a glance over a few of the files, I don't really have any domain knowledge here so can't offer any beneficial feedback but it looks ok to me.

**Comment by gnott** [comment]
> there are a lot of changes here, I'm guessing this is because it's been a while since `master` was updated?

Yup, all the code up until now has been commited to the `develop` branch, which we have been using in production environments, and the `master` branch has been unchanged since January, 2018.

This PR is a branch to branch merge, and all code going into the `master` branch is what we use in production at this time.

Eventually I hope we can make the `develop` -> `approved` -> `master` branch automation, then releases are transmitted to pypi.

It looks like this PR is green to go, I will merge it.

**Pull request merged**
