### PR TITLE
Bug fix rewrites when title_prefix is None, and remove duplicate values.

### PR DESCRIPTION
**Pull request by gnott**
Should fix edges cases where the result of ``title_prefix()`` is None, and the specific rewrites were failing. Also noticed some duplicate rewrite values and removed the duplicates.

### CODE REVIEW

**Comment by gnott** [comment]
If I understand, I think it is because a PoA article has no sub-display-channel which results in a title_prefix of None, but its VoR has a sub-display-channel in non title case, and for that we replace the value.

I could add a test for the VoR of the same article if it makes it clearer.

**Comment by giorgiosironi** [comment]
I just learned that `sub` stands for `subject` and not for `lower in hierarchy or importance`, that's enough for today :)

**Comment by gnott** [comment]
Hmmm I think the ``sub`` here is the lower in importance meaning in ``sub-display-channel``, and the subject taggging in JATS uses ``subj`` for subject.

**Comment by giorgiosironi** [comment]
Thanks for the clarification, are these in general eLife-specific terms or does JATS provide a guide?

**Comment by gnott** [comment]
I think the tag names are JATS (e.g. https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/subj-group.html) and it looks like the subj-group-type attribute is JATS but it can contain any values (https://jats.nlm.nih.gov/publishing/tag-library/1.1/attribute/subj-group-type.html) and I guess we are using eLife or JATS4R style values.

**Pull request merged**
