### PR TITLE
Feature: bumps lxml and beautifulsoup

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by lsh-0** [comment]
... I don't see any failures?

**Comment by gnott** [comment]
It might just be me then, I will get to the bottom of it.

**Comment by gnott** [comment]
This could be the cause of one of the errors: https://bugs.launchpad.net/lxml/+bug/1687236  LXML does not support unicode when building python3 and osx

**Comment by lsh-0** [comment]
are you on a mac now?

**Comment by gnott** [comment]
There are two tests with a failure/error for me on Mac, both involve unicode. 

The first is parsing the XML string `u"<p>§ <italic>*</italic></p>"` in the `test_duplicate_tag()` test. When `BeautifulSoup()` parses it, the XML node is missing.

The second is in `test_components()` only when it parses the `elife-14093-v1.xml` and does operations on it. That does have a unicode caption value, and it also calls `duplicate_tag()`.

I'll continue to see if I can refactor `duplicate_tag()` to be better. It is possibly adding some XML namespaces and then parsing the string again and maybe there's way to code that differently and avoid parsing an XML string.

**Comment by lsh-0** [comment]
are these errors only present in the upgraded version of these dependencies?

**Comment by gnott** [comment]
Only present here with the upgraded dependencies, I've been running all my tests during development in Python 3 for many months.

**Comment by lsh-0** [comment]
this was an interesting case, we don't often have Python failing just on a mac. I'm going to fyi @giorgiosironi and merge

**Comment by lsh-0** [comment]
oh - did you have a preferred merge order? https://github.com/elifesciences/elife-tools/pull/301 is still outstanding. I'll let you merge that one

**Comment by gnott** [comment]
Merge order on the same day is all good - both in now.

**Pull request merged**
